// react/components/AddTodo.js
import React from 'react'
import {addTodo} from '../store'

let AddTodo = ({ dispatch }) => {
  let input

  return (
    <form className='pure-form' onSubmit={add}>
      <fieldset>
        <input ref={node => { input = node }} />
        <button className='pure-button' type='submit'>
            Add Todo
        </button>
      </fieldset>
    </form>
  )

  function add (e) {
    e.preventDefault()
    if (!input.value.trim()) return
    addTodo(input.value)
    input.value = ''
  }
}

export default AddTodo

// angular/components/AddTodo.ts
import {Component} from '@angular/core'
import {addTodo} from '../store'

@Component({
	selector: 'AddTodo',
	template: `
		<form class="pure-form" (submit)="add(text)">
			<fieldset>
				<input [(ngModel)]="text" name="text"/>
	    	<button class="pure-button" type='submit'>
	      	Add Todo
	    	</button>
			</fieldset>
		</form>
	`
})
class AddTodo {
	text = ""
	add(text) {
		if (!text.trim()) return
		this.text = ""
		addTodo(text)
	}
}

export default AddTodo
