// react/components/TodoList.js
import React from 'react'
import {connect} from 'react-redux'
import Todo from './Todo'

let TodoList = ({ todos, onTodoClick }) => {
  return (
    <ul className='pure-menu-list'>
      { todos.map(createTodo) }
    </ul>
  )

  function createTodo (todo) {
    return <Todo key={todo.id} {...todo} />
  }
}
TodoList = connect(state => ({ todos: state }))(TodoList)

export default TodoList

// angular/components/TodoList.ts
import {Component} from '@angular/core'
import TodoStore from '../store'
import Todo from './todo'

@Component({
	selector: 'TodoList',
	template: `
		<ul class="pure-menu-list">
			<Todo *ngFor="let todo of todos" [todo]="todo"></Todo>
		</ul>
	`,
	directives: [Todo]
})
class TodoList {
	store = TodoStore;
	todos = this.store.getState()

	constructor () {
		this.store.subscribe(() => {
			this.todos = this.store.getState();
		})
	}
}

export default TodoList
