// angular/components/Todo.ts
import {Component, Input} from '@angular/core'
import {toggleTodo} from '../store'

@Component({
	selector: 'Todo',
	template: `
		<span class="pure-menu-link" [style.text-decoration]="isCompleted()" (click)="toggle()">
		{{todo.text}}
		</span>
	`
})
class Todo {
	@Input() todo
	toggle() {
		toggleTodo(this.todo.id)
	}

	isCompleted() {
		return this.todo.completed ? 'line-through' : 'none'
	}
}

export default Todo

// react/components/Todo.js
import React from 'react'
import { toggleTodo } from '../store'

const Todo = ({ id, completed, text }) => {
  return (
    <li className='pure-menu-link' onClick={toggle} style={completedStyle(completed)}>
      {text}
    </li>
  )

  function toggle () {
    toggleTodo(id)
  }
}

function completedStyle (completed) {
  return { textDecoration: completed ? 'line-through' : 'none' }
}

export default Todo
